# https://taskfile.dev

version: '3'

vars:
  BINARY_NAME: enclaude
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "0.0.0-dev"
  IMAGE_TAG: '{{.VERSION}}'
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: >-
    -X github.com/jakenelson/enclaude/internal/cli.Version={{.VERSION}}
    -X github.com/jakenelson/enclaude/internal/cli.GitCommit={{.GIT_COMMIT}}
    -X github.com/jakenelson/enclaude/internal/cli.BuildDate={{.BUILD_DATE}}

tasks:
  default:
    desc: Build the enclaude binary
    cmds:
      - task: build

  build:
    desc: Build the enclaude binary
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}} ./cmd/enclaude
    sources:
      - ./**/*.go
    generates:
      - bin/{{.BINARY_NAME}}

  install:
    desc: Install enclaude to GOPATH/bin
    cmds:
      - go install -ldflags "{{.LDFLAGS}}" ./cmd/enclaude

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
      - go clean

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  docker:build:
    desc: Build the Docker image
    cmds:
      - docker build -t enclaude:{{.IMAGE_TAG}} -t enclaude:latest -f docker/Dockerfile docker/

  docker:build-examples:
    desc: Build example Docker images
    cmds:
      - docker build -t enclaude-python:latest -f docker/examples/Dockerfile.python docker/examples/
      - docker build -t enclaude-go:latest -f docker/examples/Dockerfile.go docker/examples/

  completions:
    desc: Generate shell completions
    deps: [build]
    cmds:
      - mkdir -p completions
      - ./bin/{{.BINARY_NAME}} completion bash > completions/{{.BINARY_NAME}}.bash
      - ./bin/{{.BINARY_NAME}} completion zsh > completions/_{{.BINARY_NAME}}
      - ./bin/{{.BINARY_NAME}} completion fish > completions/{{.BINARY_NAME}}.fish

  release:
    desc: Build release binaries for multiple platforms
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-darwin-amd64 ./cmd/enclaude
      - GOOS=darwin GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-darwin-arm64 ./cmd/enclaude
      - GOOS=linux GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-linux-amd64 ./cmd/enclaude
      - GOOS=linux GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-linux-arm64 ./cmd/enclaude
